version: '3.8'

services:
  llama:
    image: ollama/ollama:latest
    container_name: jarvis-llama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - jarvis-network
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:0.4.24
    container_name: jarvis-chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/data
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      - ALLOW_RESET=TRUE
    networks:
      - jarvis-network
    restart: unless-stopped

  toolserver:
    build:
      context: ./services/toolserver
      dockerfile: Dockerfile
    container_name: jarvis-toolserver
    ports:
      - "8002:8002"
    volumes:
      - ./data:/app/data
      - ./config:/app/config:ro
    environment:
      - FACTS_DB_PATH=/app/data/facts.db
      - CHROMA_HOST=http://chroma:8000
      - CHROMA_COLLECTION=jarvis_docs
    env_file:
      - ./config/.env
    depends_on:
      - chroma
    networks:
      - jarvis-network
    restart: unless-stopped

  orchestrator:
    build:
      context: ./services/orchestrator
      dockerfile: Dockerfile
    container_name: jarvis-orchestrator
    ports:
      - "8003:8003"
    volumes:
      - ./config:/app/config:ro
    environment:
      - TOOLSERVER_URL=http://toolserver:8002
      - OLLAMA_URL=http://llama:11434
      - OLLAMA_MODEL=llama3.1
    env_file:
      - ./config/.env
    depends_on:
      - llama
      - toolserver
    networks:
      - jarvis-network
    restart: unless-stopped

  asr:
    build:
      context: ./services/asr
      dockerfile: Dockerfile
    container_name: jarvis-asr
    ports:
      - "8004:8004"
    volumes:
      - ./config:/app/config:ro
    env_file:
      - ./config/.env
    networks:
      - jarvis-network
    restart: unless-stopped

  tts:
    build:
      context: ./services/tts
      dockerfile: Dockerfile
    container_name: jarvis-tts
    ports:
      - "8005:8005"
    volumes:
      - ./config:/app/config:ro
      - tts_output:/app/output
    env_file:
      - ./config/.env
    networks:
      - jarvis-network
    restart: unless-stopped

  ingestion:
    build:
      context: ./services/ingestion
      dockerfile: Dockerfile
    container_name: jarvis-ingestion
    volumes:
      - ./data:/mnt/nas
      - ./config:/app/config:ro
    environment:
      - TOOLSERVER_URL=http://toolserver:8002
      - NAS_MOUNT_PATH=/mnt/nas
      - ENABLE_MAIL_FETCH=false
      - MAIL_FETCH_INTERVAL=300
    env_file:
      - ./config/.env
    depends_on:
      - toolserver
    networks:
      - jarvis-network
    restart: unless-stopped

  proactivity:
    build:
      context: ./services/proactivity
      dockerfile: Dockerfile
    container_name: jarvis-proactivity
    ports:
      - "8006:8006"
    volumes:
      - ./config:/app/config:ro
    environment:
      - TOOLSERVER_URL=http://toolserver:8002
      - PROACTIVITY_CONFIG=/app/config/proactivity.yml
    env_file:
      - ./config/.env
    depends_on:
      - toolserver
    networks:
      - jarvis-network
    restart: unless-stopped

networks:
  jarvis-network:
    driver: bridge

volumes:
  ollama_data:
  chroma_data:
  tts_output:
